tmpOut="/opt/FSM/adl_monitor_scripts/tmpOut.txt"
monDir="/opt/FSM/monitor/"
delayedDir="/opt/FSM/monitor/delayed/"
adlDir="/opt/FSM/adl_files/"
mailTo=DL_FSM_ALERTS_Prod@aa.com

# Call the touch script
sh /opt/FSM/adl_monitor_scripts/touchMonitorAdl.sh

# email any monitored file that has not been updated for certain number of minutes
find $monDir -maxdepth 1 -mmin +${1:-6} -type f | cut -d '/' -f 5 | while read station
do
#        echo $station
	lastFilename=$(cat $monDir$station)
	currentDate=$(date +%s)

	# If the lastFilename exist, then use that timestamp. Otherwise use the ADL monitor station last touched
	adlTouchedTime="$(date -r $monDir$station)"
	if [ -z "$lastFilename" ] || [ ! -f "$adlDir$lastFilename" ];
	then
		fileDate=$(date -r $monDir$station +%s)
		adlFileTime=""	
	else 
		fileDate=$(date -r $adlDir$lastFilename +%s)
		adlFileTime=$(date -r $adlDir$lastFilename)
	fi

	# If the elapsed time is more than 5 minutes, add to email body
	dateDiff=$(expr $(( $currentDate - $fileDate )) / 60)
	if test $dateDiff -gt 5; 
	then
		emailBody="** "$station" **  \n"
		emailBody="$emailBody Last ADL received: $lastFilename. \n"
		emailBody="$emailBody ADL received time: $adlFileTime. \n"
		emailBody="$emailBody ADL  touched time: $adlTouchedTime. \n"
		emailBody="$emailBody Current time: $(date). \n" 
		emailBody="$emailBody Elapsed time: $dateDiff minutes. \n\n"
		
		# write the time in seconds in the delayed directory if it does not already exists
		if [ ! -f "$delayedDir$station" ];
		then
			echo "$fileDate">"$delayedDir$station"
		fi
	fi

	# Append the email body output to a temp file
	if [ -n "$emailBody" ];
	then
		echo "$emailBody">>"$tmpOut"
		emailBody=""
	fi
done  

# Loop through the delayed ADLs to see if the have been restored
ls "$delayedDir" -p | grep -v / | while read station
do
	# echo "$station"
	# echo "find $adlDir$station* -maxdepth 1 -mmin -6 -type f | head -n 1 | cut -d '/' -f 5"

	# Look for files starting with the station name that appeared in the last 6 minutes
	adlFile=$(find $adlDir$station* -maxdepth 1 -mmin -6 -type f 2>/dev/null | head -n 1 | cut -d '/' -f 5 )
	if [ -n "$adlFile" ];
	then
		# Station ADL file(s) found. Add restore information to email body.
		currentDate=$(date +%s)
		fileDate=$(date -r $adlDir$adlFile +%s)
		adlFileTime=$(date -r $adlDir$adlFile)
		dateDiff=$(expr $(( $currentDate - $(cat $delayedDir$station) )) / 60)

                emailBody2="** "$station" RESTORED **  \n"
                emailBody2="$emailBody2 Last ADL received: $adlFile. \n"
                emailBody2="$emailBody2 ADL received time: $adlFileTime. \n"
                emailBody2="$emailBody2 Current time: $(date). \n"
                emailBody2="$emailBody2 Elapsed time to restore: $dateDiff minutes. \n\n"
                rm "$delayedDir$station"
	fi

        # Append the email body output to a temp file
        if [ -n "$emailBody2" ];
	then
                echo "$emailBody2">>"$tmpOut"
		emailBody2=""
	fi
done

# Email only if there delayed or restored ADL email body output
if [ -f "$tmpOut" ];
then 
	#emailBody="$(cat "$tmpOut")"
	{
        	printf "Subject: APP_Alert: Sys=PROD, Process=FSM on CAMP VM, Level=SEV3, Topic: Latent ADL from TFMS\n"
                printf "To: $mailTo \n\n"
		printf "$(cat "$tmpOut")"
                printf "For questions or removal from email distribution please contact: AAITSFSMTeam@aa.com .\n"
                printf "Message generated by FSM on CAMP at $(date -u +"%d/%b/%y/%H%Mz")"
        } | /usr/sbin/sendmail -t $mailTo

	# Remove temp email body file
	$(rm "$tmpOut")
fi

