
name: 'Zip-And-Publish-Artifact-Master'

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "docs/"
      - "images/"
      - "scripts/"
      
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "docs/"
      - "images/"
      - "scripts/"

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: FSM/
          dest: result.zip
          
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
